# -*- coding: utf-8 -*-
"""Programming Task - 3 (For Advance(EDA) .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ehRQKqK4zQ6tVdBDhK_yKzg9WHknN6e

1.Maximum Product of Two Elements in an Array
"""

class Solution:
    def maxProduct(self, nums):
        max_product = 0
        n = len(nums)

        for i in range(n):
            for j in range(i + 1, n):
                product = (nums[i] - 1) * (nums[j] - 1)
                max_product = max(max_product, product)

        return max_product

"""2.Count Number of Teams"""

class Solution:
    def numTeams(self, rating):
        n = len(rating)
        ans = 0

        for j in range(n):
            left_smaller = left_greater = 0
            right_smaller = right_greater = 0

            # left side
            for i in range(j):
                if rating[i] < rating[j]:
                    left_smaller += 1
                else:
                    left_greater += 1

            # right side
            for k in range(j + 1, n):
                if rating[k] > rating[j]:
                    right_greater += 1
                else:
                    right_smaller += 1

            ans += left_smaller * right_greater
            ans += left_greater * right_smaller

        return ans

"""3.Number of Students Doing Homework at a Given Time"""

class Solution:
    def busyStudent(self, startTime, endTime, queryTime):
        count = 0

        for i in range(len(startTime)):
            if startTime[i] <= queryTime <= endTime[i]:
                count += 1

        return count

"""4.Number of Steps to Reduce a Number to Zero"""

class Solution:
    def numberOfSteps(self, num: int) -> int:
        steps = 0

        while num > 0:
            if num % 2 == 0:
                num //= 2
            else:
                num -= 1
            steps += 1

        return steps

"""5. Counting Bits"""

class Solution:
    def countBits(self, n: int):
        ans = [0] * (n + 1)

        for i in range(1, n + 1):
            ans[i] = ans[i // 2] + (i % 2)

        return ans