# -*- coding: utf-8 -*-
"""Programming Task - 2 (For Advance(EDA).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dXpqKdmTJEY-Dog9rUJHgNzk049n4eBz

1. Defanging an IP Address
"""

class Solution:
    def defangIPaddr(self, address: str) -> str:
        return address.replace(".", "[.]")

"""2.Find Numbers with Even Number of Digits"""

class Solution:
    def findNumbers(self, nums):
        count = 0
        for num in nums:
            if len(str(num)) % 2 == 0:
                count += 1
        return count

"""3.Number of Good Pairs"""

class Solution:
    def numIdenticalPairs(self, nums):
        freq = {}
        count = 0

        for num in nums:
            if num in freq:
                count += freq[num]
                freq[num] += 1
            else:
                freq[num] = 1

        return count

"""4.How Many Numbers Are Smaller Than the Current Number

"""

class Solution:
    def smallerNumbersThanCurrent(self, nums):
        freq = [0] * 101

        # Count frequency of each number
        for num in nums:
            freq[num] += 1

        # Prefix sum to count smaller numbers
        for i in range(1, 101):
            freq[i] += freq[i - 1]

        # Build answer
        result = []
        for num in nums:
            if num == 0:
                result.append(0)
            else:
                result.append(freq[num - 1])

        return result

"""5.Subtract the Product and Sum of Digits of an Integer

"""

class Solution:
    def subtractProductAndSum(self, n: int) -> int:
        product = 1
        total = 0

        while n > 0:
            digit = n % 10
            product *= digit
            total += digit
            n //= 10

        return product - total

"""6.XOR Operation in an Array

"""

class Solution:
    def xorOperation(self, n: int, start: int) -> int:
        result = 0
        for i in range(n):
            result ^= start + 2 * i
        return result

