# -*- coding: utf-8 -*-
"""Task 1 - Analysis on ML Test Scores.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y9QAhDZJyasBpBVnkyhZ5J6t2RqsGEy_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import f_oneway

sns.set(style="whitegrid")
plt.rcParams["figure.figsize"] = (8,5)

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv(list(uploaded.keys())[0])
df.head()

print("Shape:", df.shape)
print("\nColumns:", df.columns)
print("\nInfo:")
df.info()

# Remove spaces in column names
df.columns = df.columns.str.strip()

# Clean score column ("6 / 7" → 6)
df["Score"] = (
    df["Score"]
    .astype(str)
    .str.split("/")
    .str[0]
    .str.strip()
    .astype(int)
)

df.head()

df["Score"].describe()

batch_stats = df.groupby("Batch")["Score"].agg(
    Count="count",
    Mean="mean",
    Median="median",
    Std="std",
    Min="min",
    Max="max"
).reset_index()

batch_stats

score_dist = df.groupby(["Batch", "Score"]).size().unstack(fill_value=0)
score_dist

sns.histplot(data=df, x="Score", hue="Batch", bins=8, multiple="dodge")
plt.title("Score Distribution by Batch")
plt.xlabel("Score (0–7)")
plt.ylabel("Number of Students")
plt.show()

sns.boxplot(data=df, x="Batch", y="Score")
plt.title("Batch-wise Score Comparison")
plt.show()

sns.violinplot(data=df, x="Batch", y="Score", inner="box")
plt.title("Score Density Across Batches")
plt.show()

def score_category(score):
    if score <= 2:
        return "Low"
    elif score <= 4:
        return "Medium"
    else:
        return "High"

df["Performance"] = df["Score"].apply(score_category)

pd.crosstab(df["Batch"], df["Performance"], normalize="index") * 100

batch4 = df[df["Batch"]=="AI_ELITE_4"]["Score"]
batch6 = df[df["Batch"]=="AI_ELITE_6"]["Score"]
batch7 = df[df["Batch"]=="AI_ELITE_7"]["Score"]

f_stat, p_value = f_oneway(batch4, batch6, batch7)
f_stat, p_value

df.sort_values("Score", ascending=False).groupby("Batch").head(5)

df.sort_values("Score").groupby("Batch").head(5)

Q1 = df["Score"].quantile(0.25)
Q3 = df["Score"].quantile(0.75)
IQR = Q3 - Q1

outliers = df[(df["Score"] < Q1 - 1.5*IQR) | (df["Score"] > Q3 + 1.5*IQR)]
outliers

df["Fail"] = df["Score"] <= 2
df["Excellent"] = df["Score"] >= 6

rate_table = df.groupby("Batch")[["Fail", "Excellent"]].mean() * 100
rate_table

