# -*- coding: utf-8 -*-
"""Task 2 - Diminos Case Study.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m-EzylmgwJgN3ASwb18fEanhfDluREm1
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("diminos_data.csv")

df.head()

df['order_placed_at'] = pd.to_datetime(df['order_placed_at'])
df['order_delivered_at'] = pd.to_datetime(df['order_delivered_at'])

df['delivery_time_minutes'] = (
    df['order_delivered_at'] - df['order_placed_at']
).dt.total_seconds() / 60

df['delivery_time_minutes'] = (
    df['order_delivered_at'] - df['order_placed_at']
).dt.total_seconds() / 60

# Check negative or zero delivery times
df[df['delivery_time_minutes'] <= 0]

# Check extremely large values
df[df['delivery_time_minutes'] > 120]

summary = df['delivery_time_minutes'].describe()
summary

p95 = np.percentile(df['delivery_time_minutes'], 95)
mean_time = df['delivery_time_minutes'].mean()
median_time = df['delivery_time_minutes'].median()

print("Mean Delivery Time:", round(mean_time, 2))
print("Median Delivery Time:", round(median_time, 2))
print("95th Percentile Delivery Time:", round(p95, 2))

df['sla_breach'] = df['delivery_time_minutes'] > 31

sla_breach_rate = df['sla_breach'].mean() * 100
sla_breach_rate

plt.figure(figsize=(10,5))
sns.histplot(df['delivery_time_minutes'], bins=40, kde=True)
plt.axvline(31, linestyle='--')
plt.title("Delivery Time Distribution")
plt.xlabel("Minutes")
plt.show()

Q1 = df['delivery_time_minutes'].quantile(0.25)
Q3 = df['delivery_time_minutes'].quantile(0.75)
IQR = Q3 - Q1

upper_limit = Q3 + 1.5 * IQR

outliers = df[df['delivery_time_minutes'] > upper_limit]
outliers.shape

df['order_hour'] = df['order_placed_at'].dt.hour

hourly_p95 = df.groupby('order_hour')['delivery_time_minutes'].quantile(0.95)

plt.figure(figsize=(10,5))
hourly_p95.plot(marker='o')
plt.axhline(31, linestyle='--')
plt.title("95th Percentile Delivery Time by Hour")
plt.ylabel("Minutes")
plt.xlabel("Hour")
plt.show()

df['late_night'] = df['order_hour'].apply(lambda x: 1 if x >= 1 and x <= 5 else 0)

df.groupby('late_night')['delivery_time_minutes'].quantile(0.95)

plt.figure(figsize=(12,5))
plt.plot(df['order_placed_at'], df['delivery_time_minutes'])
plt.axhline(31, linestyle='--')
plt.title("Delivery Time Over Time")
plt.show()

df_no_outliers = df[df['delivery_time_minutes'] <= 120]

np.percentile(df_no_outliers['delivery_time_minutes'], 95)

if p95 < 31:
    print("✅ Store meets Diminos SLA")
else:
    print("❌ Store FAILS Diminos SLA")

df.to_csv("diminos_with_delivery_time.csv", index=False)

